# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191164ca3bccfd895b684f339160acc63d9f2cf8c3defe0ca3174e738b2f5891287c5fd8f3e6d5394af4f563ca02c7e598ed020aafe041032905fd2c61ca8145

test:
  secret_key_base: 563e4e319ed41639d617bd08a4ad33608aacdb3e154fade3df26509a226d1f4f1ff4732da51f25e054ee589d2de46843b373d762baf90a6e8c07b74d15799aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
