default: &default
  dataset_id: <your-project-id>

development:
  <<: *default

production:
  <<: *default

# Test configuration
test:
  # Datastore
  dataset_id: gcd-test-dataset-directory
  host: http://localhost:8080/
  # SQL
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
